#!/bin/sh

dir=master-$(sed -e '/MASTER_DRIVER_VERSION /!d' \
	-e 's/[^\"]*\"\([^\"]*\)\"/\1/' include/master.h)

mkdir ${dir}
cp COPYING ${dir}
cp INSTALL ${dir}
cp Makefile ${dir}
cp mkdev.asi ${dir}
cp mkdev.fw ${dir}
cp mkdev.sdi ${dir}
cp NEWS ${dir}
cp README ${dir}

mkdir ${dir}/src
cp src/as.c ${dir}/src
cp src/asicore.c ${dir}/src
cp src/asicore.h ${dir}/src
cp src/asmi.c ${dir}/src
cp src/dvbmaster.c ${dir}/src
cp src/dvbm_fd.c ${dir}/src
cp src/dvbm_fd.h ${dir}/src
cp src/dvbm_fdu.c ${dir}/src
cp src/dvbm_fdu.h ${dir}/src
cp src/dvbm_lpfd.c ${dir}/src
cp src/dvbm_lpfd.h ${dir}/src
cp src/dvbm.h ${dir}/src
cp src/dvbm_qi.c ${dir}/src
cp src/dvbm_qi.h ${dir}/src
cp src/dvbm_qlf.c ${dir}/src
cp src/dvbm_qlf.h ${dir}/src
cp src/dvbm_qo.c ${dir}/src
cp src/dvbm_qo.h ${dir}/src
cp src/dvbm_qdual.h ${dir}/src
cp src/dvbm_qdual.c ${dir}/src
cp src/dvbm_rx.c ${dir}/src
cp src/dvbm_rx.h ${dir}/src
cp src/dvbm_rxu.c ${dir}/src
cp src/dvbm_tx.c ${dir}/src
cp src/dvbm_tx.h ${dir}/src
cp src/dvbm_txu.c ${dir}/src
cp src/eeprom.c ${dir}/src
cp src/eeprom.h ${dir}/src
cp src/gt64131.c ${dir}/src
cp src/gt64131.h ${dir}/src
cp src/jtag.c ${dir}/src
cp src/lsdma.c ${dir}/src
cp src/lsdma.h ${dir}/src
cp src/Makefile ${dir}/src
cp src/masterlsdma.c ${dir}/src
cp src/masterlsdma.h ${dir}/src
cp src/masterplx.c ${dir}/src
cp src/masterplx.h ${dir}/src
cp src/mdev.c ${dir}/src
cp src/mdev.h ${dir}/src
cp src/miface.c ${dir}/src
cp src/miface.h ${dir}/src
cp src/mmas.h ${dir}/src
cp src/mmsa.h ${dir}/src
cp src/plx9080.c ${dir}/src
cp src/plx9080.h ${dir}/src
cp src/sa.c ${dir}/src
cp src/sdicore.c ${dir}/src
cp src/sdicore.h ${dir}/src
cp src/sdimaster.c ${dir}/src
cp src/sdim.h ${dir}/src
cp src/sdim_lpfd.c ${dir}/src
cp src/sdim_qie.c ${dir}/src
cp src/sdim_qie.h ${dir}/src
cp src/sdim_qoe.c ${dir}/src
cp src/sdim_qoe.h ${dir}/src
cp src/dvbm_q3ioe.c ${dir}/src
cp src/dvbm_q3ioe.h ${dir}/src
cp src/dvbm_q3inoe.c ${dir}/src
cp src/dvbm_q3inoe.h ${dir}/src

mkdir ${dir}/include
cp include/asi.h ${dir}/include
cp include/master.h ${dir}/include
cp include/sdi.h ${dir}/include

mkdir ${dir}/doc
cp doc/buffers.txt ${dir}/doc
cp doc/examples.txt ${dir}/doc
cp doc/functions.txt ${dir}/doc
cp doc/memory.txt ${dir}/doc
cp doc/sysfs.txt ${dir}/doc

mkdir ${dir}/doc/ASI
cp doc/ASI/devices.txt ${dir}/doc/ASI
cp doc/ASI/examples.txt ${dir}/doc/ASI
cp doc/ASI/features.txt ${dir}/doc/ASI
cp doc/ASI/ioctls.txt ${dir}/doc/ASI
cp doc/ASI/sysfs.txt ${dir}/doc/ASI

mkdir ${dir}/doc/SDI
cp doc/SDI/devices.txt ${dir}/doc/SDI
cp doc/SDI/examples.txt ${dir}/doc/SDI
cp doc/SDI/features.txt ${dir}/doc/SDI
cp doc/SDI/ioctls.txt ${dir}/doc/SDI
cp doc/SDI/sysfs.txt ${dir}/doc/SDI

mkdir ${dir}/Examples
cp Examples/Makefile ${dir}/Examples
cp Examples/mastercfg.c ${dir}/Examples
cp Examples/pci_ids.h ${dir}/Examples
cp Examples/util.c ${dir}/Examples
cp Examples/util.h ${dir}/Examples

mkdir ${dir}/Examples/ASI
cp Examples/ASI/asicfg.c ${dir}/Examples/ASI
cp Examples/ASI/calcstuff.c ${dir}/Examples/ASI
cp Examples/ASI/cknull.c ${dir}/Examples/ASI
cp Examples/ASI/Makefile ${dir}/Examples/ASI
cp Examples/ASI/mknull.c ${dir}/Examples/ASI
cp Examples/ASI/rxcfg.c ${dir}/Examples/ASI
cp Examples/ASI/rxmon.c ${dir}/Examples/ASI
cp Examples/ASI/rxtest.c ${dir}/Examples/ASI
cp Examples/ASI/stampinfo.c ${dir}/Examples/ASI
cp Examples/ASI/txcfg.c ${dir}/Examples/ASI
cp Examples/ASI/txmon.c ${dir}/Examples/ASI
cp Examples/ASI/txtest.c ${dir}/Examples/ASI

mkdir ${dir}/Examples/SDI
cp Examples/SDI/capture.c ${dir}/Examples/SDI
cp Examples/SDI/eg1.c ${dir}/Examples/SDI
cp Examples/SDI/Makefile ${dir}/Examples/SDI
cp Examples/SDI/mcapture.c ${dir}/Examples/SDI
cp Examples/SDI/mplayout.c ${dir}/Examples/SDI
cp Examples/SDI/playout.c ${dir}/Examples/SDI
cp Examples/SDI/sdicfg.c ${dir}/Examples/SDI
cp Examples/SDI/sdirxcfg.c ${dir}/Examples/SDI
cp Examples/SDI/sditxcfg.c ${dir}/Examples/SDI

chmod -R go-w ${dir}
tar -c --owner=0 --group=0 -v -z -f ${dir}.tar.gz ${dir}
md5sum ${dir}.tar.gz

