/*
//       This include file was generated by tags2h
//       (do not edit this file)
*/
#ifndef TAGS_H
#define TAGS_H


/* dpxrender.c        */ double renderInterpolateDouble(int frame, int frameCount, double start, double end);
/* dpxrender.c        */ int allocateAlignedBuffer(videoBuffer_t * pVideoBuffer, unsigned int size, unsigned int alignment);
/* dpxrender.c        */ int main(int argc, char ** argv);
/* dpxrender.c        */ int renderExecute(renderThreadInfo * pThreadInfo, videoBuffer_t * pSourceBuffer, videoBuffer_t * pTargetBuffer, int frameNr);
/* dpxrender.c        */ int renderInterpolate(renderHandle * pRender, renderConfig * pConfig, int frame, int frameCount);
/* dpxrender.c        */ int startRendering(renderHandle * pRender);
/* dpxrender.c        */ void GetNextFrame(int * pFrameNr);
/* dpxrender.c        */ void * renderThread(void * p);
/* dpxrender.c        */ void signalHandler(int signal) ;
/* dpxrender_lut.c        */ void generate1DLutIdentity(void * pLut, int lutElements, int components);
/* dpxrender_lut.c        */ void generate1DLutInverse(void * pLut, int lutElements, int components);
/* dpxrender_lut.c        */ void generate3DLutIdentity(void * pLut);
/* dpxrender_lut.c        */ void generate3DLutInverse(void * pLut);

#endif
