# inspired by https://github.com/aferrero2707/appimage-testsuite
FROM archlinux
RUN pacman --noconfirm -Sy archlinux-keyring
RUN pacman-key --init
RUN pacman-key --populate
RUN pacman --noconfirm -Sy libglvnd libx11 fontconfig freetype2 jack2
