# inspired by https://github.com/aferrero2707/appimage-testsuite
# installing libraries included in https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist
FROM ubuntu:DOCKER_IMAGE_VERSION
RUN apt-get update
RUN apt-get install -y libasound2 libegl1-mesa libfontconfig1 libgl1-mesa-glx \
    libgmp10 libharfbuzz0b libopengl0 libp11-kit0 libx11-6 xvfb
