/* pci_ids.h
 *
 * Linear Systems Ltd PCI device IDs.
 *
 * Copyright (C) 2004-2009 Linear Systems Ltd. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *   3. Neither the name of Linear Systems Ltd. nor the names of its
 *      contributors may be used to endorse or promote products derived from
 *      this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY LINEAR SYSTEMS LTD. "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL LINEAR SYSTEMS LTD. OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Linear Systems can be contacted at <http://www.linsys.ca/>.
 *
 */

#ifndef _PCI_IDS_H
#define _PCI_IDS_H

#define PCI_VENDOR_ID_LINSYS 0x1254
#define PCI_DEVICE_ID_LINSYS_DVBTX 0x7629
#define PCI_DEVICE_ID_LINSYS_DVBRX 0x7630
#define PCI_DEVICE_ID_LINSYS_DVBFD 0x7643
#define PCI_DEVICE_ID_LINSYS_DVBFDU 0x0065
#define PCI_DEVICE_ID_LINSYS_DVBFDU_R 0x0066
#define PCI_DEVICE_ID_LINSYS_DVBTXU 0x0067
#define PCI_DEVICE_ID_LINSYS_DVBRXU 0x0068
#define PCI_DEVICE_ID_LINSYS_DVBQI 0x0069
#define PCI_DEVICE_ID_LINSYS_MMSA 0x006a
#define PCI_DEVICE_ID_LINSYS_SDIM 0x006b
#define PCI_DEVICE_ID_LINSYS_MMAS 0x006c
#define PCI_DEVICE_ID_LINSYS_DVBFDB 0x006d
#define PCI_DEVICE_ID_LINSYS_DVBFDB_R 0x006e
#define PCI_DEVICE_ID_LINSYS_DVB2FD 0x0073
#define PCI_DEVICE_ID_LINSYS_DVB2FD_R 0x0070
#define PCI_DEVICE_ID_LINSYS_DVB2FD_RS 0x0072
#define PCI_DEVICE_ID_LINSYS_ATSC2FD 0x0074
#define PCI_DEVICE_ID_LINSYS_ATSC2FD_R 0x0071
#define PCI_DEVICE_ID_LINSYS_ATSC2FD_RS 0x00a3
#define PCI_DEVICE_ID_LINSYS_DVBLPFD 0x0075
#define PCI_DEVICE_ID_LINSYS_SDILPFD 0x0076
#define PCI_DEVICE_ID_LINSYS_DVBQLF 0x0077
#define PCI_DEVICE_ID_LINSYS_DVBQO 0x007C
#define PCI_DEVICE_ID_LINSYS_DVBQDUAL 0x007D
#define PCI_DEVICE_ID_LINSYS_DVBQLF4 0x00B5
#define PCI_DEVICE_ID_LINSYS_SDIQI 0x00B1

/* PCI Express boards */
#define PCI_DEVICE_ID_LINSYS_DVB2FDE 0x008C
#define PCI_DEVICE_ID_LINSYS_DVB2FDE_R 0x0089
#define PCI_DEVICE_ID_LINSYS_DVB2FDE_RS 0x008B
#define PCI_DEVICE_ID_LINSYS_DVBFDE 0x0099
#define PCI_DEVICE_ID_LINSYS_DVBFDE_R 0x009A
#define PCI_DEVICE_ID_LINSYS_DVBFDEB 0x009D
#define PCI_DEVICE_ID_LINSYS_DVBFDEB_R 0x009E
#define PCI_DEVICE_ID_LINSYS_DVBTXE 0x009B
#define PCI_DEVICE_ID_LINSYS_DVBRXE 0x009C
#define PCI_DEVICE_ID_LINSYS_ATSC2FDE 0x008D
#define PCI_DEVICE_ID_LINSYS_ATSC2FDE_R 0x008A
#define PCI_DEVICE_ID_LINSYS_MMSAE 0x00a0
#define PCI_DEVICE_ID_LINSYS_SDIME 0x009f
#define PCI_DEVICE_ID_LINSYS_MMASE 0x00a1
#define PCI_DEVICE_ID_LINSYS_DVBLPFDE 0x008f
#define PCI_DEVICE_ID_LINSYS_SDIQOE 0x00B4
#define PCI_DEVICE_ID_LINSYS_SDILPFDE 0x0091
#define PCI_DEVICE_ID_LINSYS_SDIQIE 0x00A7
#define PCI_DEVICE_ID_LINSYS_DVBQDUALE 0x0086
#define PCI_DEVICE_ID_LINSYS_DVBLPQOE 0x0095
#define PCI_DEVICE_ID_LINSYS_DVBLPQOE_MINIBNC 0x00AC
#define PCI_DEVICE_ID_LINSYS_DVBQOE 0x0085
#define PCI_DEVICE_ID_LINSYS_DVBQIE 0x0084
#define PCI_DEVICE_ID_LINSYS_DVBLPQDUALE 0x0096
#define PCI_DEVICE_ID_LINSYS_DVBLPQDUALE_MINIBNC 0x00AD
#define PCI_DEVICE_ID_LINSYS_DVBLPQLF 0x00B9
#define PCI_DEVICE_ID_LINSYS_DVBLPQLF_MINIBNC 0x00BA
#define PCI_DEVICE_ID_LINSYS_DVBLPQLF_HEADER 0x00BB
#define PCI_DEVICE_ID_LINSYS_DVBQ3IOE 0x0087
#define PCI_DEVICE_ID_LINSYS_DVBQ3INOE 0x0088
#define PCI_DEVICE_ID_LINSYS_DVBLPTXE 0x00C0
#define PCI_DEVICE_ID_LINSYS_DVBLPRXE 0x00BF
#define PCI_DEVICE_ID_LINSYS_HDSDITXE 0x00C1
#define PCI_DEVICE_ID_LINSYS_HDSDIQI 0x00B6
#define PCI_DEVICE_ID_LINSYS_HDSDIRXE 0x00C8


#endif

