/*
//       This include file was generated by tags2h
//       (do not edit this file)
*/
#ifndef TAGS_H
#define TAGS_H


/* dpxio_anc.c        */ int dpxio_audio_timecode(unsigned char * buffer, int samples, int channels, int * poffset) ;
/* dpxio_anc.c        */ int dpxio_dpx_timecode(unsigned char * buffer, int dpxtype, int xsize, int * pline) ;
/* dpxio_anc.c        */ int rp215a_create(unsigned char * ancdata, int frame, int length);
/* dpxio_anc.c        */ int rp215_crc(unsigned char * ancdata, int count);
/* dpxio_anc.c        */ int rp215_create(unsigned char * ancdata, int frame, char pulldownphase, int field);
/* dpxio_anc.c        */ void rp215_dump(unsigned char * ancdata, int datacount);
/* dpxio_audio.c        */ int dpxio_audio_create(dpxio_handle * dpxio, char * filename, int format, int frequency, int channels, int nbits, int hwchannels);
/* dpxio_audio.c        */ int dpxio_audio_formatcheck(dpxio_handle * dpxio, char * filename);
/* dpxio_audio.c        */ int dpxio_audio_open(dpxio_handle * dpxio, char * filename, int hwchannels, int * pchannels, int * pfrequency);
/* dpxio_audio.c        */ int dpxio_audio_read(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, int startchannel, void * buffer, int nsamples);
/* dpxio_audio.c        */ int dpxio_audio_resample_input(dpxio_handle * dpxio, void * inputbuffer, void * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ int dpxio_audio_resample_output(dpxio_handle * dpxio, void * inputbuffer, void * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ int dpxio_audio_write(dpxio_handle * dpxio, int framenr, int startchannel, void * buffer, int nsamples);
/* dpxio_audio.c        */ void dpxio_audio_close(dpxio_handle * dpxio);
/* dpxio_audio.c        */ void dpxio_audio_resample_int16be_to_int32le(signed short * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int16le_to_int32le(signed short * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int24be_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int24le_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32be_to_int32le(int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_int16be(int * inputbuffer, signed short * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_int16le(int * inputbuffer, signed short * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_int32be(int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_int32le(int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_int8(int * inputbuffer, signed char * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_uint16be(int * inputbuffer, unsigned short * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_uint16le(int * inputbuffer, unsigned short * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_uint32be(unsigned int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_uint32le(int * inputbuffer, unsigned int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int32le_to_uint8(int * inputbuffer, unsigned char * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_int8_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint16be_to_int32le(unsigned short * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint16le_to_int32le(unsigned short * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint24be_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint24le_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint32be_to_int32le(unsigned int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint32le_to_int32le(unsigned int * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio_audio.c        */ void dpxio_audio_resample_uint8_to_int32le(unsigned char * inputbuffer, int * outputbuffer, int inputchannels, int outputchannels, int samplecount);
/* dpxio.c        */ int dpxio_dump_ancstream(short * anc, int size );
/* dpxio.c        */ int dpxio_exec(dpxio_handle * dpxio, int framecount);
/* dpxio.c        */ int dpxio_generate_ancstream(short * anc, int size, int npackets);
/* dpxio.c        */ int main(int argc, char ** argv);
/* dpxio.c        */ void dpxio_generate_ancpacket( char * anc_packet, int size, int did, int sdid, int line, int field, int packet );
/* dpxio.c        */ void dpxio_set_timecodes(dpxio_handle * dpxio, int frame, int tick, int fieldcount);
/* dpxio.c        */ void dpxio_tracelog(dpxio_handle * dpxio, int start, int count);
/* dpxio_dpx.c        */ int dpxio_dpx_closesequence(dpxio_handle * dpxio);
/* dpxio_dpx.c        */ int dpxio_dpx_framesize(dpxio_handle * dpxio, int xsize, int ysize, int dpxmode, int nbits, int * poffset, int * ppadding);
/* dpxio_dpx.c        */ int dpxio_dpx_getstoragemode(dpxio_handle * dpxio, int dpxtype, int nbits);
/* dpxio_dpx.c        */ int dpxio_dpx_opensequence(dpxio_handle * dpxio, char * filename, int firstframe, int lastframe);
/* dpxio_dpx.c        */ int dpxio_dpx_readframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int * offset, int * xsize, int * ysize, int * dpxtype, int * nbits, int * lineoffset);
/* dpxio_dpx.c        */ int dpxio_dpx_writeframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int xsize, int ysize, int dpxtype, int nbits, int offset, int padding, int timecode);
/* dpxio_jp2k.c        */ int dpxio_jp2_closesequence(dpxio_handle * dpxio);
/* dpxio_jp2k.c        */ int dpxio_jp2_framesize(dpxio_handle * dpxio, int xsize, int ysize, int dpxmode, int nbits, int * poffset, int * ppadding);
/* dpxio_jp2k.c        */ int dpxio_jp2_getstoragemode(dpxio_handle * dpxio, int dpxtype, int nbits);
/* dpxio_jp2k.c        */ int dpxio_jp2_opensequence(dpxio_handle * dpxio, char * filename, int firstframe, int lastframe);
/* dpxio_jp2k.c        */ int dpxio_jp2_readframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int * offset, int * xsize, int * ysize, int * dpxtype, int * nbits);
/* dpxio_jp2k.c        */ int dpxio_jp2_writeframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int xsize, int ysize, int dpxtype, int nbits, int offset, int padding, int timecode);
/* dpxio_lut.c        */ void dpxio_1dlut_identity(unsigned char * lut);
/* dpxio_lut.c        */ void dpxio_1dlut_invert(unsigned char * lut);
/* dpxio_lut.c        */ void dpxio_1dlutsmall_identity(unsigned char * lut);
/* dpxio_lut.c        */ void dpxio_1dlutsmall_invert(unsigned char * lut);
/* dpxio_lut.c        */ void dpxio_3dlut_identity(unsigned char * lut);
/* dpxio_lut.c        */ void dpxio_3dlut_invert(unsigned char * lut);
/* dpxio_mxf.c        */ int dpxio_mxf_closesequence(dpxio_handle * dpxio, int baudio);
/* dpxio_mxf.c        */ int dpxio_mxf_framesize(dpxio_handle * dpxio, int xsize, int ysize, int dpxmode, int nbits, int * poffset, int * ppadding);
/* dpxio_mxf.c        */ int dpxio_mxf_getstoragemode(dpxio_handle * dpxio, int dpxtype, int nbits);
/* dpxio_mxf.c        */ int dpxio_mxf_opensequence(dpxio_handle * dpxio, int baudio, char * filename, int firstframe, int lastframe);
/* dpxio_mxf.c        */ int dpxio_mxf_readaudio(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int * datasize);
/* dpxio_mxf.c        */ int dpxio_mxf_readframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int * offset, int * xsize, int * ysize, int * dpxtype, int * nbits);
/* dpxio_mxf.c        */ int dpxio_mxf_writeframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int xsize, int ysize, int dpxtype, int nbits, int offset, int padding, int timecode);
/* dpxio_mxf.c        */ int klv_get_length(char * buffer, int * length);
/* dpxio_mxf.c        */ int klv_key_compare(char * buffer, unsigned char * compare, int size);
/* dpxio_video.c        */ int dpxio_framesize(dpxio_handle * dpxio, int xsize, int ysize, int dpxmode, int nbits, int * poffset, int * ppadding);
/* dpxio_video.c        */ int dpxio_getstoragemode(dpxio_handle * dpxio, int dpxtype, int nbits);
/* dpxio_video.c        */ int dpxio_verifyformat(dpxio_handle * dpxio, char * filename, int firstframenr);
/* dpxio_video.c        */ int dpxio_video_closesequence(dpxio_handle * dpxio);
/* dpxio_video.c        */ int dpxio_video_opensequence(dpxio_handle * dpxio, char * filename, int firstframe, int lastframe);
/* dpxio_video.c        */ int dpxio_video_readframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int * offset, int * xsize, int * ysize, int * dpxtype, int * nbits, int * lineoffset);
/* dpxio_video.c        */ int dpxio_video_writeframe(dpxio_handle * dpxio, int framenr, sv_fifo_buffer * pbuffer, char * buffer, int buffersize, int xsize, int ysize, int dpxtype, int nbits, int offset, int padding, int timecode);

#endif
