'\" t
.\"     Title: hd-rum-transcode
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/26/2021
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "HD\-RUM\-TRANSCODE" "1" "05/26/2021" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hd-rum-transcode \- transcoding reflector for UltraGrid
.SH "SYNOPSIS"
.sp
\fBhd\-rum\-transcode\fR \fI[global_opts] buffer_size port [host1_options] host1 [[host2_options] host2] \&...\fR
.SH "OPTIONS"
.sp
.if n \{\
.RS 4
.\}
.nf
where global_opts may be:
        \-\-control\-port <port_number>[:0|:1] \- control port to connect to, optionally client/server (default)
        \-\-blend \- enable blending from original to newly received stream, increases latency
        \-\-conference <width>:<height>[:fps] \- enable combining of multiple inputs, increases latency
        \-\-capture\-filter <cfg_string> \- apply video capture filter to incoming video
        \-\-param \- additional parameters
        \-\-help
        \-\-verbose
        \-v \- print version
and hostX_options may be:
        \-P [<rx_port>:]<tx_port> \- TX port to be used (optionally also RX)
        \-c <compression> \- compression
        Following options will be used only if \*(Aq\-c\*(Aq parameter is set:
        \-m <mtu> \- MTU size
        \-l <limiting_bitrate> \- bitrate to be shaped to
        \-f <fec> \- FEC that will be used for transmission\&.
        \-6 \- use IPv6
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
Please note that blending and capture filter is used only for host for which compression is specified (transcoding is active)\&. If compression is not set, simple packet retransmission is used\&. Compression can be also\(cqnone\*(Aq for uncompressed transmission (see\(cquv \-c help\*(Aq for list)\&.
.sp
Transcoder can be used as a reflector also for audio (and must be used if audio is deployed)\&. It doesn\(cqt have, however, any transcoding facilities for audio\&. Only port remapping can be used for audio\&.
.SH "EXAMPLES"
.SS "Basic example"
.sp
\fBhd\-rum\-transcode\fR 8M 5004 receiver1 receiver2 \-c JPEG receiver3 # video \fBhd\-rum\-transcode\fR 8M 5006 receiver1 receiver2 receiver3 # audio \- no transcoding
.SS "Reflector running on UltraGrid sender machine"
.sp
\fBuv\fR \-t testcard \-s testcard \fI\-P 6004:5004:6006:5006\fR localhost \fBhd\-rum\-transcode\fR 8M 5004 receiver1 receiver2 \-c JPEG receiver3 # video \fBhd\-rum\-transcode\fR 8M 5006 receiver1 receiver2 receiver3 # audio
.SH "ENVIRONMENT VARIABLES"
.PP
\fBULTRAGRID_VERBOSE\fR
.RS 4
If is
ULTRAGRID_VERBOSE
environment variable is set, default UltraGrid log level is
verbose\&. Command\-line option always overrides this value\&.
.RE
.SH "REPORTING BUGS"
.sp
Report bugs to \fBultragrid\-dev@cesnet\&.cz\fR or use project \fBGitHub\fR to describe issues\&.
.SH "RESOURCES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GitHub:
\fBhttps://github\&.com/CESNET/UltraGrid\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Wiki (on\-line documentation):
\fBhttps://github\&.com/CESNET/UltraGrid/wiki\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Main web site:
\fBhttp://www\&.ultragrid\&.cz\fR
.RE
.SH "SEE ALSO"
.sp
hd\-rum(1) uv(1)
