'\" t
.\"     Title: uv
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/01/2023
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "UV" "1" "03/01/2023" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
uv \- UltraGrid command line interface
.SH "SYNOPSIS"
.sp
\fBuv\fR [\fIOPTIONS\fR] \fIADDRESS\fR
.SH "OPTIONS"
.sp
.if n \{\
.RS 4
.\}
.nf
\-h | \-\-fullhelp                 show usage (basic/full)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-d <display_device>             select display device, use \*(Aq\-d help\*(Aq
                                to get list of supported devices
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-t <capture_device>             select capture device, use \*(Aq\-t help\*(Aq
                                to get list of supported devices
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-c <cfg>                        video compression (see \*(Aq\-c help\*(Aq)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-r <playback_device>            audio playback device (see \*(Aq\-r help\*(Aq)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-s <capture_device>             audio capture device (see \*(Aq\-s help\*(Aq)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-verbose[=<level>]             print verbose messages (optionally specify level [0\-8])
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-list\-modules                  prints list of modules
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-control\-port <port>[:0|1]     set control port (default port: 5054)
                                connection types: 0\- Server (default), 1\- Client
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-video\-protocol <proto>        transmission protocol, see \*(Aq\-\-video\-protocol help\*(Aq
                                for list\&. Use \-\-video\-protocol rtsp for RTSP server
                                (see \-\-video\-protocol rtsp:help for usage)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-protocol <proto>[:<settings>] <proto> can be JACK, rtsp, sdp or ultragrid_rtp
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-protocol <proto>              shortcut for \*(Aq\-\-audio\-protocol <proto> \-\-video\-protocol <proto>\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-4/\-6                           force IPv4/IPv6 resolving
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-mcast\-if <iface>              bind to specified interface for multicast
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-m <mtu>                        set path MTU assumption towards receiver
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-M <video_mode>                 received video mode (eg tiled\-4K, 3D,
                                dual\-link)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-N|\-\-nat\-traverse               try to deploy NAT traversal techniques
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-p <postprocess> | help         postprocess module
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-T|\-\-ttl <num>                  Use specified TTL for multicast/unicast (0\&.\&.255, \-1 for default)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-f [A:|V:]<settings>            FEC settings (audio or video) \- use
                                "none", "mult:<nr>",
                                "ldgm:<max_expected_loss>%%" or
                                "ldgm:<k>:<m>:<c>"
                                "rs:<k>:<n>"
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-P <port> | <video_rx>:<video_tx>[:<audio_rx>:<audio_tx>]
                                <port> is base port number, also 3
                                subsequent ports can be used for RTCP
                                and audio streams\&. Default: 5004\&.
                                You can also specify all two or four
                                ports directly\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-l <limit_bitrate> | unlimited | auto limit sending bitrate
                                to <limit_bitrate> (with optional k/M/G suffix)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-A <address>                    audio destination address
                                If not specified, will use same as for video
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-capture\-format <fmt> | help format of captured audio
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-channel\-map <mapping> | help
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-filter <filter>[:<config>][#<filter>[:<config>]]\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-codec <codec>[:sample_rate=<sr>][:bitrate=<br>] | help audio codec
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-delay <delay_ms>        amount of time audio should be delayed to video
                                (may be also negative to delay video)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-audio\-scale <factor> | <method> | help scales received audio
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-echo\-cancellation             apply acoustic echo cancellation to audio (experimental)
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-cuda\-device <index> | help    use specified GPU
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-encryption <passphrase>       key material for encryption
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-playback <directory> | help   replays recorded audio and video
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-record[=<directory>]          record captured audio and video
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-F|\-\-capture\-filter <filter> | help capture filter(s), must be given before capture device
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-param <params> | help         additional advanced parameters, use help for list
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-pix\-fmts                      list of pixel formats
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-conv\-policy [cds]{3} | help   pixel format conversion policy
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-video\-codecs                  list of video codecs
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
address                         destination address
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT VARIABLES"
.PP
\fBULTRAGRID_VERBOSE\fR
.RS 4
If is
ULTRAGRID_VERBOSE
environment variable is set, default UltraGrid log level is
verbose\&. Command\-line option always overrides this value\&.
.RE
.SH "REPORTING BUGS"
.sp
Report bugs to \fBultragrid\-dev@cesnet\&.cz\fR or use project \fBGitHub\fR to describe issues\&.
.SH "RESOURCES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
GitHub:
\fBhttps://github\&.com/CESNET/UltraGrid\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Wiki (on\-line documentation):
\fBhttps://github\&.com/CESNET/UltraGrid/wiki\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Main web site:
\fBhttp://www\&.ultragrid\&.cz\fR
.RE
.SH "SEE ALSO"
.sp
hd\-rum\-transcode(1)
