#!/bin/sh

# Receive kernel versions
MAJOR=`uname -r | awk -v FS="." '{print $1}'`
MINOR=`uname -r | awk -v FS="." '{print $2}'`
PATCH=`uname -r | awk -v FS="." '{print $3}' | awk -v FS="-" '{print $1}'` 

KERNEL=/lib/modules/`uname -r`/build
if [ -e /lib/modules/`uname -r`/source ]; then
  KERNEL=/lib/modules/`uname -r`/source
fi

if ! [ -d $KERNEL/kernel ]; then
  echo "There is no kernel source installed for the running kernel `uname -r`."
  exit 1
fi
if ! [ -f $KERNEL/.config ]; then
  echo "The kernel source for `uname -r` is not configured."
  exit 1
fi
if ! [ -L $KERNEL/include/asm ]; then
  echo "The kernel source for `uname -r` seems not to be configured properly."
  exit 1
fi
if ! [ -f $KERNEL/include/linux/version.h ]; then
  echo "The kernel source for `uname -r` seems not to be compiled properly."
  exit 1
fi

# Check if regparm is activated in the current kernel
REGPARM=`cat $KERNEL/.config | grep CONFIG_REGPARM | grep -cw y`

if [ $MAJOR -eq "2" ]; then
  if [ $MINOR -eq "6" ]; then
    if [ $PATCH -ge "20" ]; then
      #Force REGPARM on 2.6.20 kernels.
      REGPARM=1
    fi
  fi
fi

export HOSTTYPE
export OSTYPE=linux

make -C ../../development/src/driver clean
make -C ../../development/src/driver COMPILE_REGPARM=$REGPARM

make -C ../../development/src_sdio/driver clean
make -C ../../development/src_sdio/driver COMPILE_REGPARM=$REGPARM
