#!/bin/sh

# Receive kernel versions
MAJOR=`uname -r | awk -v FS="." '{print $1}'`
MINOR=`uname -r | awk -v FS="." '{print $2}'`
PATCH=`uname -r | awk -v FS="." '{print $3}' | awk -v FS="-" '{print $1}'` 

KERNEL=/lib/modules/`uname -r`/build
if [ -e /lib/modules/`uname -r`/source ]; then
  KERNEL=/lib/modules/`uname -r`/source
fi

if ! [ -d $KERNEL/kernel ]; then
  echo "There is no kernel source installed for the running kernel `uname -r`."
  exit 1
fi

# Check if regparm is activated in the current kernel
REGPARM=`cat $KERNEL/.config | grep CONFIG_REGPARM | grep -cw y`

if [ $MAJOR -eq "2" ]; then
  if [ $MINOR -eq "6" ]; then
    if [ $PATCH -ge "20" ]; then
      #Force REGPARM on 2.6.20 kernels.
      REGPARM=y
    fi
  fi
fi

export HOSTTYPE
export OSTYPE=linux

# Clean
make -C ../../development/src_lucy/driver DRIVERNAME=dvsdriver_lucy clean
make -C ../../development/src_v4r3/driver DRIVERNAME=dvsdriver_v4r3 clean
make -C ../../development/src_lucy/driver DRIVERNAME=dvsdebug_lucy  clean
make -C ../../development/src_v4r3/driver DRIVERNAME=dvsdebug_v4r3  clean

# Check 64 bit
if [ `uname -m` = "x86_64" ]; then
  make -C ../../development/src_lucy/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdriver_lucy  PATH_BIN=../../../linux-x86_64/driver/
  make -C ../../development/src_v4r3/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdriver_v4r3  PATH_BIN=../../../linux-x86_64/driver/
  make -C ../../development/src_lucy/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdebug_lucy   PATH_BIN=../../../linux-x86_64/driver/
  make -C ../../development/src_v4r3/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdebug_v4r3   PATH_BIN=../../../linux-x86_64/driver/
else
  make -C ../../development/src_lucy/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdriver_lucy  PATH_BIN=../../../linux-x86/driver/
  make -C ../../development/src_v4r3/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdriver_v4r3  PATH_BIN=../../../linux-x86/driver/
  make -C ../../development/src_lucy/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdebug_lucy   PATH_BIN=../../../linux-x86/driver/
  make -C ../../development/src_v4r3/driver  CONFIG_REGPARM=$REGPARM  DRIVERNAME=dvsdebug_v4r3   PATH_BIN=../../../linux-x86/driver/
fi

# Copy drive into driver dir
cp ../../development/src_lucy/driver/dvsdriver_lucy.ko .
cp ../../development/src_v4r3/driver/dvsdriver_v4r3.ko .
cp ../../development/src_lucy/driver/dvsdebug_lucy.ko .
cp ../../development/src_v4r3/driver/dvsdebug_v4r3.ko .
