#!/bin/bash
#
# Script that creates the dvs device nodes
#
echo ""
echo "Trying to create DVS driver device nodes:"

if [ "$(id -u)" != "0" ]; then
  echo "- This script must be run as root."
  exit 1
fi

if ! lsmod | grep dvs > /dev/null ; then
  echo " - Unable to find the driver."
  echo "   Please make sure that the .ko file was created and the driver loaded"
  exit 1
fi

if ! [ -d /proc/dvsdriver -o -d /proc/dvsdriver_v4r3 -o -d /proc/dvsdriver_lucy ]; then
  echo " - Unable to find a video board."
  echo "   Please make sure that a video board is installed."
  exit 1
fi

# Remove old device nodes
#########################
  rm -rf /dev/iris*
  rm -rf /dev/lucy*
  rm -rf /dev/hugo*
  rm -rf /dev/jpeg*
  rm -rf /dev/v4r3*
  rm -rf /dev/digilab* 
  rm -rf /dev/clipboard*
  rm -rf /tmp/dvs_device_list

# Create one tmp file with all devices
######################################
  for i in `find /proc/dvsdriver*/cards`
  do
    cat $i >> /tmp/dvs_device_list
  done

# Calculate how much lines are in this file
###########################################
  LINES=`wc /tmp/dvs_device_list | awk '{print $1}'`

# Create all device nodes
#########################
  for((LINE=1, CLIP=0; $LINE <= $LINES; LINE++,CLIP++)); 
  do
    TMP=`cat /tmp/dvs_device_list | head -n $LINE | tail -n 1`
    mknod `echo $TMP | awk '{print "-m 666 /dev/" $1 " c " $2 " " $3}'`
    echo "Created device: `echo $TMP | awk '{print "/dev/" $1 " " $2 " " $3}'`"
    
    # Create old device nodes
    ln -s `echo $TMP | awk '{print "/dev/" $1}'` /dev/clipboard$CLIP
  done

# Delete tmp file
#################
  rm -rf /tmp/dvs_device_list
