test:
	g++ -g -DASTAT_DEBUG -DDEFINE_TEST_MAIN astat.cpp ../src/compat/platform_pipe.cpp -I../src -pthread -o astat_test

lib:
	g++ -fpic -shared astat.cpp ../src/compat/platform_pipe.cpp -I../src -pthread -o astat.so
