test:
	g++ -g -DASTAT_DEBUG -DDEFINE_TEST_MAIN astat.cpp ../src/compat/platform_pipe.cpp -I../src -pthread -o astat_test

lib:
	g++ -DHAVE_CONFIG_H -fpic -c -std=c++11 astat.cpp ../src/compat/platform_pipe.cpp -I../src -pthread
	ar rcs astat.a astat.o platform_pipe.o
