#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root."
  exit 1
fi

if lsmod | grep dvsdriver.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdriver"
  rmmod dvsdriver.ko
elif lsmod | grep dvsdebug.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdebug"
  rmmod dvsdebug.ko
elif lsmod | grep dvsdriver > /dev/null 2>&1 ; then
  echo "- unload dvsdriver"
  rmmod dvsdriver
elif lsmod | grep dvsdebug > /dev/null 2>&1 ; then
  echo "- unload dvsdebug"
  rmmod dvsdebug
fi

if lsmod | grep dvsdriver_lucy.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdriver_lucy"
  rmmod dvsdriver_lucy.ko
elif lsmod | grep dvsdebug_lucy.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdebug_lucy"
  rmmod dvsdebug_lucy.ko
elif lsmod | grep dvsdriver_lucy > /dev/null 2>&1 ; then
  echo "- unload dvsdriver_lucy"
  rmmod dvsdriver_lucy
elif lsmod | grep dvsdebug_lucy > /dev/null 2>&1 ; then
  echo "- unload dvsdebug_lucy"
  rmmod dvsdebug_lucy
fi

if lsmod | grep dvsdriver_v4r3.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdriver_v4r3"
  rmmod dvsdriver_v4r3.ko
elif lsmod | grep dvsdebug_v4r3.ko > /dev/null 2>&1 ; then
  echo "- unload dvsdebug_v4r3"
  rmmod dvsdebug_v4r3.ko
elif lsmod | grep dvsdriver_v4r3 > /dev/null 2>&1 ; then
  echo "- unload dvsdriver_v4r3"
  rmmod dvsdriver_v4r3
elif lsmod | grep dvsdebug_v4r3 > /dev/null 2>&1 ; then
  echo "- unload dvsdebug_v4r3"
  rmmod dvsdebug_v4r3
fi

exit 0
