# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2019-2026 CESNET, zájmové sdružení právnických osob

name: C/C++ CI

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.*
    paths:
      - '.github/scripts/**'
      - '.github/workflows/ccpp.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - '**.c'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.m'
      - '**.mm'
      - 'autogen.sh'
      - 'configure.ac'
      - 'data/**'
      - 'Makefile.in'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, we do not need to create own token.
    steps:
    - uses: actions/checkout@v4
      id: checkout
      with:
        persist-credentials: true
    - name: Init environment variables
      run: . .github/scripts/environment.sh
    - name: Retag continuous
      if: github.repository == 'CESNET/UltraGrid' && github.ref == 'refs/heads/master'
      run: |
        git fetch --prune --unshallow --tags
        git tag -f $TAG
        git push -f origin refs/tags/$TAG:refs/tags/$TAG
    - name: Update Release
      if: (github.repository == 'CESNET/UltraGrid' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags/')
      run: .github/scripts/create_release.sh
    - name: Create continuous release # ensure continuous release is present for AppImage zsync
      if: startsWith(github.ref, 'refs/tags/')
      run: .github/scripts/create_continuous_release.sh

  Ubuntu:
    needs: prepare
    uses: ./.github/workflows/linux.yml

  macOS:
    needs: prepare
    uses: ./.github/workflows/macos.yml

  Windows:
    needs: prepare
    uses: ./.github/workflows/windows.yml
